server.port=9080
logging.level.org.atmosphere = warn

# To improve the performance during development. 
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters

